language: rust

script:
- cargo build --verbose --features="$FEATURES"
- cargo test --verbose --features="$FEATURES"

branches:
  only:
    - master

rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  include:
  - rust: stable
    env: FEATURES="preserve_order"
  - rust: beta
    env: FEATURES="preserve_order"
  - rust: nightly
    env: FEATURES="preserve_order"
