language: rust
cache: cargo

branches:
  only:
    - master

# run builds for all the trains (and more)
rust:
  - stable
  - beta
  - nightly

matrix:
  fast_finish: true
  include:
  - rust: stable
    env: FEATURES="preserve_order"
  - rust: beta
    env: FEATURES="preserve_order"
  - rust: nightly
    env: FEATURES="preserve_order"

script:
- cargo build --verbose --features="$FEATURES"
- cargo test --verbose --features="$FEATURES"
